[2023-12-10T07:05:59.807+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: taskflow.load_Orders_to_bigquery manual__2023-12-10T07:04:34.099937+00:00 [queued]>
[2023-12-10T07:06:01.995+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: taskflow.load_Orders_to_bigquery manual__2023-12-10T07:04:34.099937+00:00 [queued]>
[2023-12-10T07:06:02.156+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-12-10T07:06:03.242+0000] {taskinstance.py:1382} INFO - Executing <Task(GCSToBigQueryOperator): load_Orders_to_bigquery> on 2023-12-10 07:04:34.099937+00:00
[2023-12-10T07:06:03.384+0000] {standard_task_runner.py:57} INFO - Started process 1510 to run task
[2023-12-10T07:06:04.023+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'taskflow', 'load_Orders_to_bigquery', 'manual__2023-12-10T07:04:34.099937+00:00', '--job-id', '132', '--raw', '--subdir', 'DAGS_FOLDER/test_decorator.py', '--cfg-path', '/tmp/tmp_nfpwfcy']
[2023-12-10T07:06:05.136+0000] {standard_task_runner.py:85} INFO - Job 132: Subtask load_Orders_to_bigquery
[2023-12-10T07:06:25.805+0000] {task_command.py:416} INFO - Running <TaskInstance: taskflow.load_Orders_to_bigquery manual__2023-12-10T07:04:34.099937+00:00 [running]> on host 580ab8862310
[2023-12-10T07:06:41.949+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='taskflow' AIRFLOW_CTX_TASK_ID='load_Orders_to_bigquery' AIRFLOW_CTX_EXECUTION_DATE='2023-12-10T07:04:34.099937+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-10T07:04:34.099937+00:00'
[2023-12-10T07:06:45.242+0000] {connection.py:232} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2023-12-10T07:06:45.814+0000] {base.py:73} INFO - Using connection ID 'google_cloud_datastore_default' for task execution.
[2023-12-10T07:06:46.265+0000] {gcs_to_bigquery.py:376} INFO - Using existing BigQuery table for storing data...
[2023-12-10T07:06:46.370+0000] {credentials_provider.py:353} INFO - Getting connection using `google.auth.default()` since no explicit credentials are provided.
[2023-12-10T07:06:48.178+0000] {bigquery.py:2311} INFO - Project is not included in destination_project_dataset_table: dataset_for_dag_testing.Orders; using project "northwind-qu"
[2023-12-10T07:06:48.227+0000] {gcs_to_bigquery.py:380} INFO - Executing: {'load': {'autodetect': True, 'createDisposition': 'CREATE_IF_NEEDED', 'destinationTable': {'projectId': 'northwind-qu', 'datasetId': 'dataset_for_dag_testing', 'tableId': 'Orders'}, 'sourceFormat': 'CSV', 'sourceUris': ['gs://us-central1-test-env-b4f32c38-bucket/data/Orders.csv'], 'writeDisposition': 'WRITE_TRUNCATE', 'ignoreUnknownValues': False, 'skipLeadingRows': 1, 'fieldDelimiter': ',', 'quote': None, 'allowQuotedNewlines': False, 'encoding': 'UTF-8'}}
[2023-12-10T07:06:48.459+0000] {bigquery.py:1595} INFO - Inserting job ***_taskflow_load_Orders_to_bigquery_2023_12_10T07_04_34_099937_00_00_ad2cf87402693938cb4a246445c20165
[2023-12-10T07:06:58.985+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=taskflow, task_id=load_Orders_to_bigquery, execution_date=20231210T070434, start_date=20231210T070559, end_date=20231210T070658
[2023-12-10T07:07:00.153+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-12-10T07:07:02.571+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
