[2023-12-08T23:58:22.424+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: taskflow.extract manual__2023-12-08T23:58:20.998454+00:00 [queued]>
[2023-12-08T23:58:22.430+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: taskflow.extract manual__2023-12-08T23:58:20.998454+00:00 [queued]>
[2023-12-08T23:58:22.431+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 0
[2023-12-08T23:58:22.439+0000] {taskinstance.py:1382} INFO - Executing <Task(_PythonDecoratedOperator): extract> on 2023-12-08 23:58:20.998454+00:00
[2023-12-08T23:58:22.445+0000] {standard_task_runner.py:57} INFO - Started process 1787 to run task
[2023-12-08T23:58:22.449+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'taskflow', 'extract', 'manual__2023-12-08T23:58:20.998454+00:00', '--job-id', '68', '--raw', '--subdir', 'DAGS_FOLDER/test_decorator.py', '--cfg-path', '/tmp/tmp4gzt7o94']
[2023-12-08T23:58:22.453+0000] {standard_task_runner.py:85} INFO - Job 68: Subtask extract
[2023-12-08T23:58:22.505+0000] {task_command.py:416} INFO - Running <TaskInstance: taskflow.extract manual__2023-12-08T23:58:20.998454+00:00 [running]> on host 3de6e37e1218
[2023-12-08T23:58:22.583+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='taskflow' AIRFLOW_CTX_TASK_ID='extract' AIRFLOW_CTX_EXECUTION_DATE='2023-12-08T23:58:20.998454+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-08T23:58:20.998454+00:00'
[2023-12-08T23:58:22.588+0000] {python.py:194} INFO - Done. Returned value was: {'all_path': [PosixPath('/opt/airflow/data/northwind_gitRepo/northwind_gitRepo/tables/Customers.csv'), PosixPath('/opt/airflow/data/northwind_gitRepo/northwind_gitRepo/tables/Categories.csv'), PosixPath('/opt/airflow/data/northwind_gitRepo/northwind_gitRepo/tables/Products.csv'), PosixPath('/opt/airflow/data/northwind_gitRepo/northwind_gitRepo/tables/Orders.csv'), PosixPath('/opt/airflow/data/northwind_gitRepo/northwind_gitRepo/tables/Suppliers.csv'), PosixPath('/opt/airflow/data/northwind_gitRepo/northwind_gitRepo/tables/CustomerCustomerDemo.csv'), PosixPath('/opt/airflow/data/northwind_gitRepo/northwind_gitRepo/tables/Shippers.csv'), PosixPath('/opt/airflow/data/northwind_gitRepo/northwind_gitRepo/tables/Territories.csv'), PosixPath('/opt/airflow/data/northwind_gitRepo/northwind_gitRepo/tables/Employees.csv'), PosixPath('/opt/airflow/data/northwind_gitRepo/northwind_gitRepo/tables/Region.csv'), PosixPath('/opt/airflow/data/northwind_gitRepo/northwind_gitRepo/tables/EmployeeTerritories.csv'), PosixPath('/opt/airflow/data/northwind_gitRepo/northwind_gitRepo/tables/CustomerDemographics.csv'), PosixPath('/opt/airflow/data/northwind_gitRepo/northwind_gitRepo/tables/Order_details.csv')]}
[2023-12-08T23:58:22.594+0000] {xcom.py:661} ERROR - Object of type PosixPath is not JSON serializable. If you are using pickle instead of JSON for XCom, then you need to enable pickle support for XCom in your *** config or make sure to decorate your object with attr.
[2023-12-08T23:58:22.595+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/json.py", line 91, in default
    return serialize(o)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/serialization/serde.py", line 178, in serialize
    raise TypeError(f"cannot serialize object of type {cls}")
TypeError: cannot serialize object of type <class 'pathlib.PosixPath'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2479, in xcom_push
    XCom.set(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/xcom.py", line 244, in set
    value = cls.serialize_value(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/xcom.py", line 659, in serialize_value
    return json.dumps(value, cls=XComEncoder).encode("UTF-8")
  File "/usr/local/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/json.py", line 104, in encode
    return super().encode(o)
  File "/usr/local/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/json.py", line 93, in default
    return super().default(o)
  File "/usr/local/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type PosixPath is not JSON serializable
[2023-12-08T23:58:22.607+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=taskflow, task_id=extract, execution_date=20231208T235820, start_date=20231208T235822, end_date=20231208T235822
[2023-12-08T23:58:22.616+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 68 for task extract (Object of type PosixPath is not JSON serializable; 1787)
[2023-12-08T23:58:22.623+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-08T23:58:22.641+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
